### ISSUE TITLE
If this action is used multiple times, the post-action to delete netrc will fail

### ISSUE THREAD

**Issue by gobetti** [extractions/netrc#11]
I need to add 2 different servers so my setup looks like this:
```
  - uses: extractions/netrc@v2
    with:
      machine: github.com
      username: <username>
      password: <password>
  - uses: extractions/netrc@v2
    with:
      machine: maven.pkg.github.com
      username: <username>
      password: <password>
```

but I believe each of these will call the post-action from #9 , and because the first call will have deleted the netrc file already, subsequent attempts fail with:
```
ENOENT: no such file or directory, unlink '/Users/runner/.netrc'
```
